["external/license-list-data"]
path = "external/license-list-data"
url = "https://github.com/spdx/license-list-data.git"
shallow = true
branch = "main"
ignore = "all"

fetch = "on-demand"

["external/choosealicense.com"]
path = "external/choosealicense.com"
url = "https://github.com/github/choosealicense.com.git"
shallow = true
branch = "gh-pages"
ignore = "all"
fetch = "on-demand"



["external/license-list-XML"]
path = "external/license-list-XML"
url = "https://www.github.com/spdx/license-list-XML.git"
branch = "main"
ignore = "all"
active = true
sparse_paths = ["/*", "!/*/", "/equivalentwords.txt/", "/schema/", "/src/"]
