[tasks]
[tasks.gentypes]
run = "bunx wrangler -c ./wrangler.json types"

[tasks.build]
depends = ["gentypes"]
run = "bunx wrangler -c ./wrangler.json build"

[tasks.deploy]
depends = ["build"]
run = "bunx wrangler -c ./wrangler.json deploy"
