import { defineCollection } from "./utils";

export const seriesCollection = defineCollection({
  label: "Series",
  name: "series",
  folder: "/content/blog/series",
  label_singular: "Series",
  create: true,
  delete: true,
  format: "toml",
  sortable_fields: ["name"],
  icon: "view_carousel",
  extension: "toml",
  slug: "{{name | slugify}}",
  fields: [
    {
      label: "Name of the series (e.g. 'MIT License Explained')",
      name: "name",
      widget: "string",
    },
    {
      label: "Description of the series",
      name: "description",
      widget: "text",
    },
    {
      label: "Catchy tagline for the series",
      name: "tagline",
      widget: "string",
      required: false,
      maxlength: 120,
      hint: "A short, catchy description of the series to draw readers in ~100 characters.",
    },
    {
      label: "UUID",
      name: "uuid",
      widget: "hidden",
      readonly: true,
      default: "{{uuid}}",
    },
    {
      label: "Posts in this series",
      name: "posts",
      widget: "list",
      collection: "blog-posts",
      search_fields: ["title", "authors.*.name"],
      value_field: "uuid",
      required: false,
      display_fields: ["{{title}}", "{{index}}"],
      allow_reorder: true,
    },
    {
      label: "Authors of the series",
      name: "authors",
      widget: "hidden",
      default: "{{fields.posts.*.authors.*.name | unique}}",
      value_type: "list",
      required: false,
    },
  ],
});

export const tagsCollection = defineCollection({
  name: "blog-tags",
  label: "Blog Tags",
  label_singular: "Tag",
  folder: "/content/blog/tags",
  create: true,
  delete: true,
  extension: "toml",
  format: "toml",
  icon: "tag",
  slug: "{{name | slugify}}",
  identifier_field: "name",
  sortable_fields: {
    fields: ["name"],
    default: { field: "name", direction: "ascending" },
  },
  summary: "{{name}}",
  fields: [
    {
      name: "name",
      label: "Tag Name",
      widget: "string",
      maxlength: 30,
      required: true,
    },
    {
      name: "description",
      label: "Description",
      widget: "text",
      required: false,
    },
    {
      name: "slug",
      label: "Slug",
      widget: "compute",
      required: true,
      value: "{{fields.name | slugify}}",
    },
    {
      name: "uuid",
      label: "Tag ID",
      widget: "hidden",
      required: false,
      default: "{{uuid}}",
    },
  ],
});

export const featuredPostsCollection = defineCollection({
  name: "featured",
  label: "Featured Posts",
  label_singular: "Featured Post",
  folder: "/content/featured",
  format: "json",
  extension: "json",
  slug: "{{slug}}",
  icon: "star",
  limit: 5,
  filter: {
    field: "featuredPosts.*.post.featured",
    value: true,
  },
  fields: [
    {
      name: "featuredPosts",
      label: "Featured Posts",
      widget: "list",
      required: true,
      add_to_top: true,
      allow_duplicates: false,
      allow_reorder: true,
      label_singular: "Featured Post",
      search_fields: ["post.title", "post.publication_date"],
      collapsed: true,
      limit: 5,
      summary:
        "{{fields.post.title | truncate(30)}} — {{fields.post.publication_date | date('YYYY-MM-DD')}}",
      field: {
        name: "post",
        label: "Post",
        widget: "relation",
        collection: "blog-posts",
        search_fields: [
          "title",
          "description",
          "authors.*.name",
          "tags.*.name",
        ],
        value_field: "uuid",
        display_fields: ["title"],
        filters: [
          {
            field: "featured",
            values: [true],
          },
          {
            field: "status",
            values: ["published"],
          },
        ],
        sortable_fields: {
          fields: [
            "publication_date",
            "title",
            "tags.*.name",
            "authors.*.name",
          ],
          default: { field: "publication_date", direction: "descending" },
        },
      },
    },
  ],
});

export const blogPostsCollection = defineCollection({
  name: "blog-posts",
  label: "Blog Posts",
  folder: "/content/blog/posts",
  create: true,
  delete: true,
  format: "yaml-frontmatter",
  extension: "mdx",
  thumbnail: "title_image",
  slug: "{{fields.title | slugify}}",
  identifier_field: "uuid",
  sortable_fields: [
    "title",
    "creation_date",
    "publication_date",
    "last_updated",
    "authors.*.name",
    "status",
  ],
  summary: "{{title | truncate(50)}} ({{creation_date | date('YYYY-MM-DD')}})",
  label_singular: "Blog Post",
  icon: "article",
  fields: [
    { label: "Title", name: "title", widget: "string" },
    {
      label: "Creation Date",
      name: "creation_date",
      widget: "hidden",
      readonly: true,
      required: false,
      default: "{{date | date('YYYY-MM-DDTHH:mm:ssZ')}}",
    },
    {
      label: "Publication Date",
      name: "publication_date",
      widget: "hidden",
      readonly: true,
      required: false,
      // no default - set by the publication hook
      default: "",
    },
    {
      label: "Last Updated",
      name: "last_updated",
      widget: "hidden",
      readonly: true,
      required: false,
      default: "{{date | date('YYYY-MM-DDTHH:mm:ssZ')}}",
    },
    {
      label: "Authors",
      name: "authors",
      widget: "list",
      collection: "authors",
      multiple: true,
      display_fields: ["{{authors.*.name}}"],
      search_fields: ["{{authors.*.name}}"],
      value_field: "{{authors.*.uuid}}",
      required: false,
    },
    {
      label: "Description",
      name: "description",
      widget: "text",
      hint: "1-3 sentences, answers 'what's this post about?'. Markdown supported.",
      required: false,
    },
    {
      label: "Tags",
      name: "tags",
      widget: "relation",
      collection: "blog-tags",
      search_fields: ["name"],
      value_field: "uuid",
      required: false,
    },
    {
      label: "Category",
      name: "category",
      widget: "select",

      options: [
        "announcements",
        "guides",
        "updates",
        "community",
        "license-talk",
      ],
      required: false,
    },
    {
      label: "Featured",
      name: "featured",
      widget: "boolean",
      default: false,
      required: false,
    },
    {
      label: "Title Image",
      name: "title_image",
      widget: "image",
      required: false,
    },
    {
      label: "OG Image",
      name: "og_image",
      widget: "image",
      required: false,
    },
    {
      label: "Related Licenses",
      name: "related_licenses",
      widget: "relation",
      multiple: true,
      collection: "licenses",
      search_fields: ["title", "plain_name", "spdx_id", "original.name"],
      value_field: "uuid",
      required: false,
    },
    {
      label: "Status",
      name: "status",
      widget: "select",
      options: ["draft", "published"],
      default: "draft",
    },
    {
      label: "UUID",
      name: "uuid",
      widget: "hidden",
      readonly: true,
      required: false,
      default: "{{uuid}}",
    },
    {
      label: "Series",
      name: "series",
      widget: "relation",
      collection: "series",
      search_fields: ["name"],
      value_field: "uuid",
      required: false,
      multiple: false,
    },
    { label: "Body", name: "body", widget: "richtext" },
  ],
});
