import { defineCollection } from "./utils";

export const licensesCollection = defineCollection({
  name: "licenses",
  label: "Licenses",
  folder: "content/licenses",
  path: "{{license_family}}/{{slug}}",
  label_singular: "License",
  icon: "license",
  extension: "md",
  format: "yaml-frontmatter",
  create: true,
  delete: false,
  identifier_field: "plain_name",
  sortable_fields: {
    fields: ["plain_name", "spdx_id", "license_family", "status"],
    default: { field: "plain_name", direction: "ascending" },
  },
  view_filters: [
    {
      field: "status",
      label: "Drafts",
      pattern: "draft",
    },
    {
      field: "status",
      label: "Published",
      pattern: "published",
    },
    {
      field: "featured",
      label: "Featured",
      pattern: true,
    },
    {
      field: "license_family",
      label: "Open Source",
      pattern: "permissive|copyleft|public-domain",
    },
  ],
  view_groups: [
    {
      field: "license_family",
      label: "License family",
    },
    {
      field: "status",
      label: "Status",
    },
  ],
  fields: [
    // Zone 1 - Identity
    // title defaults to the plain name
    {
      label: "Title",
      name: "title",
      widget: "string",
      required: false,
    },
    {
      label: "Plain language name (e.g. 'Plain MIT License')",
      name: "plain_name",
      widget: "string",
      pattern: "^Plain [A-Z][A-Za-z0-9 -.]+",
      required: true,
    },
    {
      label: "Plain ID",
      name: "plain_id",
      hint: "A unique identifier for this plain license, derived from the original license's SPDX ID. It should be in the format (case depending on usage): 'Plain-[SPDX ID with version suffixes removed]'. For example, 'Plain-MIT' or 'Plain-Apache'. This is used in URLs and as a stable identifier for the license. If the license doesn't have an original SPDX ID, create a unique identifier that follows the same format.",
      widget: "hidden",
      readonly: true,
      required: true,
      default: "",
    },
    {
      label: "SPDX ID",
      name: "spdx_id",
      comment:
        "The SPDX ID of *the plain license* if it has one (currently none do), not the original license. The original license's SPDX ID, if applicable, goes in the 'original' field.",
      widget: "string",
      required: false,
    },
    {
      label: "Version of this plain language version",
      name: "plain_version",
      widget: "hidden",
      default: "0.1.0",
      readonly: true,
    },
    {
      name: "license_family",
      label: "License family",
      widget: "select",
      options: [
        "public-domain",
        "permissive",
        "copyleft",
        "source-available",
        "proprietary",
      ],
      multiple: false,
      comment:
        "Family of the license. If it has no requirements at all, it's probably public domain. If it has minimal requirements, like just attribution, it's probably permissive. If it doesn't allow changes, relicensing, or sharing it's proprietary. If it allows some changes and sharing but has restrictions on how you can use it, like commercially, it's source-available (sources available but not open source). If it allows changes, sharing, and commercial use but requires you share alike, it's copyleft.",
      required: true,
    },
    {
      label: "Is this a public domain dedication (not a license)?",
      name: "is_dedication",
      widget: "hidden",
      default: false,
      required: false,
    },
    {
      label: "Status",
      name: "status",
      widget: "select",
      options: ["draft", "published"],
      default: "draft",
      required: true,
    },
    {
      label:
        "Description (1–3 sentences, answers 'what kind of license is this?')",
      name: "description",
      widget: "text",
      required: false,
    },
    {
      name: "tldr",
      label:
        "TL;DR — 2 to 4 bullets (answers 'what do I need to know right now?')",
      widget: "list",
      field: { widget: "string" },
    },
    // Zone 3 - Conditions
    {
      label: "Requires attribution?",
      name: "attribution_required",
      widget: "boolean",
      default: true,
      required: false,
    },
    {
      label: "Additional how-to instructions (leave blank for most licenses)",
      name: "extra_how",
      widget: "richtext",
      required: false,
    },
    // Display controls
    {
      label: "Show original comparison?",
      name: "show_original_comparison",
      widget: "boolean",
      default: true,
      required: false,
    },
    {
      label: "Show shame counter?",
      name: "show_shame_counter",
      widget: "boolean",
      default: true,
      required: false,
    },
    {
      label: "Featured?",
      name: "featured",
      widget: "boolean",
      default: false,
      required: false,
    },
    {
      label: "Fair Code license?",
      name: "fair_code",
      widget: "boolean",
      default: false,
      required: false,
    },
    // === License finder / recommendations ===
    {
      label:
        "Maker pitch (one-liner for license finder results, max 120 chars)",
      name: "maker_pitch",
      widget: "string",
      required: false,
    },
    {
      name: "commercial_restrictions",
      label: "Commercial restrictions",
      widget: "select",
      multiple: true,
      required: false,
      options: [
        "no-managed-service",
        "no-selling",
        "network-copyleft",
        "time-delayed-open",
      ],
    },
    {
      name: "compare_to",
      label: "Compare to (for license finder 'also consider' results)",
      widget: "list",
      required: false,
      fields: [
        {
          label: "SPDX ID of the license to compare against",
          name: "spdx_id",
          widget: "string",
        },
        {
          label:
            "Contrast statement (e.g. 'Like MIT, but without the credit requirement')",
          name: "contrast",
          widget: "string",
        },
      ],
    },
    // SEO fields (optional overrides for auto-generated values)
    {
      label: "Meta description (overrides auto-generated)",
      name: "meta_description",
      widget: "string",
      required: false,
    },
    {
      label: "OG Image",
      name: "og_image",
      widget: "image",
      required: false,
    },
    {
      label: "Authors",
      name: "authors",
      widget: "relation",
      collection: "authors",
      multiple: true,
      display_fields: ["{{fields.*.name}}"],
      search_fields: ["{{fields.*.name}}"],
      value_field: "{{fields.*.uuid}}",
      required: false,
    },
    {
      label: "Changelog",
      name: "changelog",
      widget: "richtext",
      required: false,
    },
    {
      label: "UUID",
      name: "uuid",
      widget: "hidden",
      readonly: true,
      value: "{{uuid}}",
    },
    // Readability metrics (computed at build time)
    {
      label: "Readability: Gunning Fog",
      name: "plain_gunning_fog",
      widget: "hidden",
      readonly: true,
      default: 0,
      value_type: "float",
      required: false,
    },
    {
      label: "Shame Words Count",
      name: "shame_words_count",
      widget: "hidden",
      readonly: true,
      default: 0,
      value_type: "int",
      required: false,
    },
    {
      label: "Original license (leave blank for PlainLicense originals)",
      name: "original",
      widget: "object",
      required: false,
      fields: [
        {
          label: "Full original name (e.g. 'MIT License')",
          name: "name",
          widget: "string",
        },
        {
          label: "Alternative names (e.g. 'Expat License')",
          name: "alternative_names",
          widget: "list",
          required: false,
        },
        {
          label: "SPDX identifier",
          name: "spdx_id",
          widget: "string",
          required: false,
        },
        {
          label: "Version (raw, e.g. '2.0')",
          name: "version",
          widget: "string",
          pattern: "^[0-9]+\\.[0-9]+$",
          required: false,
        },
        {
          label: "Display version (e.g. 'MIT License (1988)')",
          name: "version_display",
          widget: "string",
          required: false,
        },
        {
          label: "Steward organization",
          name: "organization",
          widget: "string",
          required: false,
        },
        {
          label: "Has a single official authoritative source?",
          name: "has_official_source",
          widget: "boolean",
          default: false,
        },
        {
          label: "Canonical URL",
          name: "canonical_url",
          widget: "string",
          required: false,
          hint: "The URL of the official source for the license text, if it has one. This is used in the 'original text' comparison view to link to the original license.",
        },
        {
          label: "Gunning Fog of original license text",
          name: "original_gunning_fog",
          widget: "hidden",
          readonly: true,
          default: 0,
          value_type: "float",
          required: false,
        },
        {
          label:
            "Does the original text include a link to its own canonical URL?",
          name: "link_in_original",
          widget: "boolean",
          default: false,
          required: false,
        },
        {
          label: "Deprecated in SPDX?",
          name: "is_deprecated",
          widget: "hidden",
          default: false,
          required: false,
        },
        {
          label: "OSI Approved",
          name: "is_osi_approved",
          widget: "boolean",
          required: false,
        },
        {
          label: "FSF Approved",
          name: "is_fsf_approved",
          widget: "boolean",
          required: false,
        },
        {
          name: "permissions",
          label: "Permissions (choosealicense.com tags)",
          widget: "select",
          multiple: true,
          required: false,
          options: [
            "commercial-use",
            "distribution",
            "modifications",
            "patent-use",
            "private-use",
            "revokable",
          ],
        },
        {
          name: "conditions",
          label: "Conditions (choosealicense.com tags)",
          widget: "select",
          multiple: true,
          required: false,
          options: [
            "disclose-source",
            "document-changes",
            "include-copyright",
            "include-copyright--source",
            "network-use-disclose",
            "same-license",
            "same-license--file",
            "same-license--library",
          ],
        },
        {
          name: "limitations",
          label: "Limitations (choosealicense.com tags)",
          widget: "select",
          multiple: true,
          required: false,
          options: ["liability", "patent-use", "trademark-use", "warranty"],
        },
      ],
    },
    // Per-license extended term definitions (for terms unique to this license)
    {
      name: "defined_terms",
      label: "Extended term definitions",
      widget: "list",
      required: false,
      hint: "Terms unique to this license that need visible definitions (e.g. 'contributor', 'managed service'). Global terms like 'share', 'the work' are handled automatically.",
      fields: [
        {
          label: "Term",
          name: "term",
          widget: "string",
          required: true,
        },
        {
          label: "Hover text (short, for tooltip)",
          name: "hover",
          widget: "string",
          required: true,
        },
        {
          label: "Footnote text (longer, for exports)",
          name: "footnote",
          widget: "text",
          required: true,
        },
        {
          label: "Show in visible definition section?",
          name: "show_definition",
          widget: "boolean",
          default: true,
        },
      ],
    },
    {
      label: "Body",
      name: "body",
      widget: "richtext",
      editor_components: ["code-block", "image", "footnote"],
    },
  ],
});
